owner: Artiges-Lab
repo: weivo-status
user-agent: Artiges-Lab
sites:
- name: Weivo App
  url: https://app.weivo.io
- name: Weivo Marketing Website
  url: https://weivo.io
status-website:
  cname: status.weivo.io
  name: Weivo Status
